# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui',
# licensing of 'MainWindow.ui' applies.
#
# Created: Mon Oct 14 14:50:14 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1229, 854)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_scanning = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_scanning.setGeometry(QtCore.QRect(460, 80, 661, 141))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(60)
        self.lineEdit_scanning.setFont(font)
        self.lineEdit_scanning.setText("")
        self.lineEdit_scanning.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_scanning.setObjectName("lineEdit_scanning")
        self.label_scanning = QtWidgets.QLabel(self.centralwidget)
        self.label_scanning.setGeometry(QtCore.QRect(40, 80, 361, 131))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(50)
        font.setWeight(75)
        font.setBold(True)
        self.label_scanning.setFont(font)
        self.label_scanning.setObjectName("label_scanning")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(40, 450, 1081, 121))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(50)
        self.label_status.setFont(font)
        self.label_status.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.label_status.setText("")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.label_previous_barcode = QtWidgets.QLabel(self.centralwidget)
        self.label_previous_barcode.setGeometry(QtCore.QRect(40, 260, 361, 131))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(50)
        font.setWeight(75)
        font.setBold(True)
        self.label_previous_barcode.setFont(font)
        self.label_previous_barcode.setObjectName("label_previous_barcode")
        self.lineEdit_previous_barcode = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_previous_barcode.setGeometry(QtCore.QRect(460, 260, 661, 141))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(60)
        self.lineEdit_previous_barcode.setFont(font)
        self.lineEdit_previous_barcode.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_previous_barcode.setText("")
        self.lineEdit_previous_barcode.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_previous_barcode.setReadOnly(True)
        self.lineEdit_previous_barcode.setObjectName("lineEdit_previous_barcode")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(670, 610, 451, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_IP = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_IP.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_IP.setObjectName("lineEdit_IP")
        self.horizontalLayout.addWidget(self.lineEdit_IP)
        self.pushButton_change_ip = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setWeight(50)
        font.setBold(False)
        self.pushButton_change_ip.setFont(font)
        self.pushButton_change_ip.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1.2, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(200, 194, 15);")
        self.pushButton_change_ip.setObjectName("pushButton_change_ip")
        self.horizontalLayout.addWidget(self.pushButton_change_ip)
        self.pushButton_plc_connect_test = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setWeight(50)
        font.setBold(False)
        self.pushButton_plc_connect_test.setFont(font)
        self.pushButton_plc_connect_test.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1.2, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(200, 194, 15);")
        self.pushButton_plc_connect_test.setObjectName("pushButton_plc_connect_test")
        self.horizontalLayout.addWidget(self.pushButton_plc_connect_test)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1229, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.lineEdit_scanning, QtCore.SIGNAL("returnPressed()"), MainWindow.barcode_scanning)
        QtCore.QObject.connect(self.pushButton_change_ip, QtCore.SIGNAL("clicked()"), MainWindow.change_ip)
        QtCore.QObject.connect(self.pushButton_plc_connect_test, QtCore.SIGNAL("clicked()"), MainWindow.connect_test)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label_scanning.setText(QtWidgets.QApplication.translate("MainWindow", "条码扫描:", None, -1))
        self.label_previous_barcode.setText(QtWidgets.QApplication.translate("MainWindow", "上次条码:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "PLC的IP:", None, -1))
        self.lineEdit_IP.setText(QtWidgets.QApplication.translate("MainWindow", "192.168.0.255", None, -1))
        self.pushButton_change_ip.setText(QtWidgets.QApplication.translate("MainWindow", "设置为当前值", None, -1))
        self.pushButton_plc_connect_test.setText(QtWidgets.QApplication.translate("MainWindow", "测试连接", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

